frankfurter:
    quota_limit: 999999999 # Unlimited (Free)
    failover_to: null
    priority: 1

exchangerate:
    quota_limit: 50
    failover_to: currencylayer
    priority: 2

currencylayer:
    quota_limit: 100
    failover_to: null
    priority: 3
