[destination.filesystem]
bucket_url = "s3://bronze-bucket"

[destination.filesystem.credentials]
aws_access_key_id = "minioadmin"
aws_secret_access_key = "minioadmin123"
# endpoint_url = "http://minio:9000"  # Docker network service name
# region_name = "us-east-1"

